-- Lmod module file for <PIPELINE> <VERSION>
-- Generated by nf-ood-mod

help([[
   This module loads the OOD app for <PIPELINE> version <VERSION>.
   The OOD app lives in:
   $HOME/<OOD_ROOT>/<PIPELINE>-<VERSION>
]])

whatis("Name: <PIPELINE>")
whatis("Version: <VERSION>")
whatis("Category: bioinformatics")
whatis("Description: OOD app for <PIPELINE> version <VERSION>")

-- The OOD UI expects the app to be under $HOME/<OOD_ROOT>
setenv("OOD_APP_ROOT", pathJoin(os.getenv("HOME"), "<OOD_ROOT>"))
